### ISSUE TITLE
error compiling!

### ISSUE THREAD

**Issue by start141** [hiteshsondhi88/ffmpeg-android#10]
I just run sudo apt-get --quiet --yes install build-essential git autoconf libtool pkg-config gperf gettext yasm，but 404 error，what's wrong whith this error?

After this operation, 55.1 MB of additional disk space will be used.
Err http://us.archive.ubuntu.com/ubuntu/ raring/main libsigsegv2 amd64 2.9-4ubuntu3
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main autoconf all 2.69-1ubuntu1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main autotools-dev all 20120608.1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main automake all 1:1.11.6-1ubuntu1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main libstdc++6-4.7-dev amd64 4.7.3-1ubuntu1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main g++-4.7 amd64 4.7.3-1ubuntu1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main g++ amd64 4:4.7.3-1ubuntu10
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main dpkg-dev all 1.16.10ubuntu1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main build-essential amd64 11.6ubuntu4
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main git-man all 1:1.8.1.2-1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main git amd64 1:1.8.1.2-1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main gperf amd64 3.0.3-1ubuntu2
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main libltdl-dev amd64 2.4.2-1.2ubuntu1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main libtool amd64 2.4.2-1.2ubuntu1
  404  Not Found [IP: 91.189.91.23 80]
Err http://us.archive.ubuntu.com/ubuntu/ raring/main yasm amd64 1.2.0-1
  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/libs/libsigsegv/libsigsegv2_2.9-4ubuntu3_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/a/autoconf/autoconf_2.69-1ubuntu1_all.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/a/autotools-dev/autotools-dev_20120608.1_all.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/a/automake1.11/automake_1.11.6-1ubuntu1_all.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.7/libstdc++6-4.7-dev_4.7.3-1ubuntu1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.7/g++-4.7_4.7.3-1ubuntu1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g++_4.7.3-1ubuntu10_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.16.10ubuntu1_all.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/build-essential_11.6ubuntu4_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/git/git-man_1.8.1.2-1_all.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/git/git_1.8.1.2-1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gperf/gperf_3.0.3-1ubuntu2_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/libt/libtool/libltdl-dev_2.4.2-1.2ubuntu1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/libt/libtool/libtool_2.4.2-1.2ubuntu1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/y/yasm/yasm_1.2.0-1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by hiteshsondhi88** [comment]
Try to update the apt repo first, and then proceed with above
