### ISSUE TITLE
Youtube/Whatsapp videos not getting cropped/cut

### ISSUE THREAD

**Issue by bhuvneshvarma** [hiteshsondhi88/ffmpeg-android#15]
I have added below dependency.

    compile 'com.github.hiteshsondhi88.libffmpeg:FFmpegAndroid:0.2.5'

I am using below command 

    execFFmpegBinary("-i " + path + " -ss " + startMs / 1000 + " -to " + endMs / 1000 + " -strict -2 -async 1 " + dest.getAbsolutePath());
to cut or trim videos.

Its working for some videos but for some videos its NOT working especially for videos that are shared from whatssapp or downloaded from youtube.It gives below error..I am using `Environment.getExternalStoragePublicDirectory( Environment.DIRECTORY_MOVIES )` for storage of videos.

    FAILED with output : WARNING: linker: /files/ffmpeg has text relocations. This is wasting memory and prevents security hardening. Please fix.
        ffmpeg version n2.4.2 Copyright (c) 2000-2014 the FFmpeg developers
        built on Oct  7 2014 15:11:41 with gcc 4.8 (GCC)
        configuration: --target-os=linux --cross-prefix=/home/sb/Source-Code/ffmpeg-android/toolchain-android/bin/i686-linux-android- --arch=x86 --cpu=i686 --enable-runtime-cpudetect --sysroot=/home/sb/Source-Code/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/sb/Source-Code/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/sb/Source-Code/ffmpeg-android/build/x86 --extra-cflags='-I/home/sb/Source-Code/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -march=i686' --extra-ldflags='-L/home/sb/Source-Code/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
        libavutil      54.  7.100 / 54.  7.100
        libavcodec     56.  1.100 / 56.  1.100
        libavformat    56.  4.101 / 56.  4.101
        libavdevice    56.  0.100 / 56.  0.100
        libavfilter     5.  1.100 /  5.  1.100
        libswscale      3.  0.100 /  3.  0.100
        libswresample   1.  1.100 /  1.  1.100
        libpostproc    53.  0.100 / 53.  0.100
        /storage/emulated/0/1: No such file or directory

  [1]: https://github.com/hiteshsondhi88/ffmpeg-android

**Comment by mdtuyen** [comment]
I have the same issue. Could you please shared your solution with me ?
