### ISSUE TITLE
Use fontconfig

### ISSUE THREAD

**Issue by lightlz** [hiteshsondhi88/ffmpeg-android#17]
Hi,

I use your another project(ffmpeg-android-java) to burn subtitles in the video,and execute:

`ffmpeg -y -i input.mp4 -vf subtitles=input.srt -c:v mpeg4 -c:a aac -strict -2 output.mp4`

but it doesn’t work well.

You told me that I should create the custom fontconfig,so I tried to rebuild the SO.
I’m able to get ffmpeg(bulid/xx/bin) files,but I don’t know how to specify the custom fontconfig config file.
I create a fonts.conf file and place it into my sdcard(`storage/sdcard/`).
Can you tell me how to configure? 
Thank you!

**Comment by hiteshsondhi88** [comment]
@lightlz please check the Instructions
