### ISSUE TITLE
Build failing: ./configure. No such file or directory

### ISSUE THREAD

**Issue by viacheslavokolitiy** [hiteshsondhi88/ffmpeg-android#2]
Hello everyone. Unfortunately, this library could not be built, just following instructions in README,  on latest version of Lubuntu i686 on step ./android_build.sh i receive build error. Any ideas to fix the build ?

**Comment by karanbalkar** [comment]
I am facing the same issue.
The error is as follows:

make: *** No rule to make target 'clean'.  Stop.
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all
./x264_build.sh: line 21: ./configure: No such file or directory

Trying to build the same on Ubuntu 15.04 (64 bit OS)

Please suggest a solution for the same.

**Comment by JayParikh20** [comment]
@karanbalkar Make Sure your Submodules/Subfolder are not empty , i was having the same problem

**Comment by adancygier** [comment]
Same issue for me, its failing in configure for me with 64 bit ubuntu

uname -a
XXX 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adancygier** [comment]
I think what happened for me is the x264 submodule failed to update and the directory was empty.  Reinitializing it fixed the problem.
